LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := libSwJpgCodec
LOCAL_SRC_FILES := libSwJpgCodec.so
LOCAL_SHARED_LIBRARIES := libmtkjpeg libstdc++
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
include $(BUILD_PREBUILT)
