LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := libGLESv1_CM_mali
LOCAL_SRC_FILES := libGLESv1_CM_mali.so
LOCAL_SHARED_LIBRARIES := libMali libmtk_mali_user libstdc++
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/egl
include $(BUILD_PREBUILT)
