LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := libMtkOmxG711Dec
LOCAL_SRC_FILES := libMtkOmxG711Dec.so
LOCAL_SHARED_LIBRARIES := libbinder libstdc++ libui
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
include $(BUILD_PREBUILT)
